<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ag</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>AttributeGrammer</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(if|while|for|return)\b</string>
			<key>name</key>
			<string>keyword.control.untitled</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^({)(\s*\n)?</string>
			<key>contentName</key>
			<string>source.haskell.embedded.ag</string>
			<key>end</key>
			<string>^(})</string>
			<key>name</key>
			<string>meta.function.embedded.haskell.ag</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.haskell</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\|</string>
			<key>contentName</key>
			<string>source.haskell.embedded.ag</string>
			<key>end</key>
			<string>--\|</string>
			<key>name</key>
			<string>meta.function.embedded.haskell.ag</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.haskell</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>::\s*\{</string>
			<key>contentName</key>
			<string>source.haskell.embedded.ag</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.function.embedded.haskell.ag</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.haskell</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.untitled</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(attr|sem|syn|inh|@loc|@lhs|include|module|data|imports|around|attach|type|pragma|self|use|deriving)\b</string>
			<key>name</key>
			<string>keyword.other.AttributeGrammer</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block_comment</key>
		<dict>
			<key>applyEndPatternLast</key>
			<integer>1</integer>
			<key>begin</key>
			<string>\{-(?!#)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.haskell</string>
				</dict>
			</dict>
			<key>end</key>
			<string>-\}</string>
			<key>name</key>
			<string>comment.block.AG</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block_comment</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.AG</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(--).*$\n?</string>
					<key>name</key>
					<string>comment.line.double-dash.AG</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block_comment</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ag</string>
	<key>uuid</key>
	<string>ECE4C55A-F6A4-4D3A-93E9-30C0FC78A0B5</string>
</dict>
</plist>
